# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "1220a81facdcb6cb3676ac1189c35477540854d31c17d63cf3bdc8b94452f781d286";
    path = fetchzip {
      url = "https://github.com/MFAshby/zig-build-zlib/archive/f7f6262574fbfffd0202b4ad881a0cec1c7c189b.tar.gz";
      hash = "sha256-OHt9LjONGHj7KZAD0IM+kDIC7PgLVQY2LUiJBy7qr50=";
    };
  }
  {
    name = "1220be3870d531f0b2560f2de80593cf6d6950f97da940d90b0e4ed8c7e7f112dbaa";
    path = fetchzip {
      url = "https://github.com/nih-at/libzip/releases/download/v1.10.1/libzip-1.10.1.tar.gz";
      hash = "sha256-Q7Zw4JLhm3Sq/ghwsjWyyuqX8J6yzCOo692yE/yUA/s=";
    };
  }
]
